### ISSUE TITLE
Is it possible to provide `psql` command?

### ISSUE THREAD

**Issue by hank-cp** [Harmon758/postgresql-action#3]

**Comment by Mystraht** [comment]
+1, is it possible?
Hank-cp, did you resolve your issue?

**Comment by hank-cp** [comment]
@Mystraht looks like it's not very possible to achieve this goal. If you want to use `psql` to do some initialization jobs, take consideration of this PR #2.

**Comment by Mystraht** [comment]
I resolved my issue by naming my container and using docker exec to use psql command.

    on: push
    name: Main
    jobs:
      symfony:
        name: Symfony PHP 7.1
        runs-on: ubuntu-latest
        services:
          postgres:
            image: postgres:9.6
            options: --name=postgres
            ports:
              - 5432/tcp

Then:

`docker exec -d postgres psql YOUR_ARGS`

**Comment by gmassman** [comment]
Thank you @Mystraht! Been pulling out my hair since yesterday trying to figure this out.

**Comment by Mystraht** [comment]
@gmassman glad it help someone :)
